feat: 업종에 대한 가게 전체 DB에 insert기능 추가
wanted-7h/hotplace pull request #45
Opened 2023-11-03 12:25 UTC by sphy1597

2023-11-04 03:03 UTC, Yonge2 approved these changes

2023-11-04 10:28 UTC, scarf005 reviewed
![image](https://github.com/wanted-7h/hotplace/assets/54838975/6f627c6c-f22c-40ea-9800-3214d257b05d)

혹시 기능구현이 완료되었을까요?

2023-11-06 07:49 UTC, scarf005 requested changes
README 머지 충돌 해결 또한 필요할 것 같습니다

2023-11-06 07:49 UTC, scarf005 commented on src/scheduler/all_insert.ts
> +  const key = process.env.api_key;
`README.md`에 `api_key`를 얻는 방법을 설명해주시면 실행에 도움이 될 것 같아요!

2023-11-06 07:50 UTC, sphy1597 commented on src/scheduler/all_insert.ts
> +  const key = process.env.api_key;
일단은 readme에 간단하게 작성해 놓으면 될까요 ?

2023-11-06 07:58 UTC, sphy1597 commented on src/scheduler/all_insert.ts
> +  const key = process.env.api_key;
추가했습니다!

2023-11-06 08:05 UTC, scarf005 approved these changes

2023-11-06 08:11 UTC, scarf005 commented on src/scheduler/all_insert.ts
> +    const getHead = await axios.get(getHeadUrl);
node 21부터 [fetch API](https://nodejs.org/docs/latest-v21.x/api/globals.html#fetch)가 정식 지원되는 만큼, 웹 표준인 [fetch API](https://developer.mozilla.org/ko/docs/Web/API/Fetch_API)를 사용해도 좋을 것 같아요!

- https://stackoverflow.com//questions/35038857/setting-query-string-using-fetch-get-request#answer-58437909

2023-11-06 08:11 UTC, merged