feat: Refreshtoken 핸들링
wanted-7h/hotplace pull request #70
Opened 2023-11-07 03:16 UTC by Yonge2

레디스를 이용한 리프래시 토큰 유효성 검증과 재발급 과정을 추가했습니다.

close #48

2023-11-07 04:30 UTC, scarf005 requested changes

2023-11-07 04:30 UTC, scarf005 commented on src/redis.ts
> +});
```suggestion
await redisClient.connect();
console.log("redis is connected");
```

## Promise.then()

[`Promise.then`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then)을 사용해 주셨는데, [언제 Promise가 resolve되고 then이 실행되는지 예측할 수 없으므로](https://chat.openai.com/share/2c86a9ee-dc87-4d7c-8c11-cffb6d3137c6), redis 연결을 마치기 전에 redis에 메시지 보내기를 시도하는 등의 동기화 문제가 발생할 수 있을 것 같아요

## await

#55, #66을 통해 [ECMAScript 모듈](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Modules)로 전환하여 [top-level await](https://nodejs.org/dist/latest-v20.x/docs/api/esm.html#top-level-await)이 사용 가능해졌습니다.

때문에, 이 경우에는 대신 [await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await)을 사용하는 것이 더 적절할 것 같습니다.

2023-11-07 10:48 UTC, Yonge2 commented on src/user/auth/auth_router.ts
> +        : undefined;
jwt payload 인터페이스 확장선언으로 해결하였습니다!

2023-11-07 10:49 UTC, Yonge2 commented on src/user/authorization/jwtUtils.ts
> +    }
중복 try catch 제거하여 조금 더 간결하게 수정했습니다!

2023-11-08 05:41 UTC, scarf005 commented on src/user/authorization/jwtUtils.ts
> +  60 * 60 * 24 * Number(process.env.RT_EXPIRED_BY_NUMBER);
```suggestion
  60 * 60 * 24 * Number(process.env.RT_EXPIRED_BY_NUMBER || 1);
```
`process.env`에 `RT_EXPIRED_BY_NUMBER`가 정의되지 않았을 시 #76 과 같은 오류가 발생합니다. 추후에 환경 변수를 zod 스키마로 파싱하고 기본값을 주는 식으로 바꾸면 될 것 같아요!

2023-11-08 05:43 UTC, Yonge2 commented on src/user/authorization/jwtUtils.ts
> +  60 * 60 * 24 * Number(process.env.RT_EXPIRED_BY_NUMBER);
아하 이 부분을 제가 놓쳤었군요 ㅠ 확인 감사합니다!

2023-11-08 06:06 UTC, scarf005 reviewed
GET /auth에서 다음과 같은 오류가 발생합니다.

```
GET /auth 500 6.043 ms - 779
Error: Bad "options.expiresIn" option the payload already has an "exp" property.
    at Object.module.exports (/home/scarf/repo/etc/hotplace/node_modules/jsonwebtoken/sign.js:163:20)
    at createAccessToken (/home/scarf/repo/etc/hotplace/src/user/authorization/jwtUtils.ts:12:7)
    at reissueAccessToken (/home/scarf/repo/etc/hotplace/src/user/auth/auth_router.ts:50:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async mainReqHandler (file:///home/scarf/repo/etc/hotplace/node_modules/@ts-rest/express/index.mjs:78:28)
```

2023-11-08 06:12 UTC, scarf005 approved these changes

2023-11-08 06:15 UTC, merged

2023-11-08 06:17 UTC, Yonge2 commented
아 재발급 시, 페이로드에서 시작일 만료일을 뺐어야되는데, 그대로 써버렸네요 리펙토링하면서 고치겠습니다!

2023-11-08 06:42 UTC, scarf005 commented
아, 제가 머지하면서 [c73d5c5f20dd467e8f30fce83329d740c80f4066](https://github.com/wanted-7h/hotplace/commit/c73d5c5f20dd467e8f30fce83329d740c80f4066) 에서 수정했어요!