refactor: 유저정보 업데이트 시, 액세스토큰 발급으로 변경
wanted-7h/hotplace pull request #71
Opened 2023-11-07 04:18 UTC by Yonge2

토큰 내에 유저가 요청에 필요한 정보들을 담아서 사용하는데,
정보 업뎃을 하면 토큰 내 정보가 유효하지 않습니다.

그래서 업데이트 후 엑세스 토큰 재발급으로 변경했습니다.

close #58

2023-11-07 05:37 UTC, scarf005 requested changes

2023-11-07 05:37 UTC, scarf005 commented on src/user/userInfo/userInfo_router.ts
> +      //리펙토링 필요
zod 스키마로 headers에서 user를 파싱하면 어떨까요?

2023-11-07 06:18 UTC, Yonge2 commented on src/user/userInfo/userInfo_router.ts
> +      //리펙토링 필요
수업 끝나고 시도해보겠습니다!

2023-11-08 09:28 UTC, scarf005 approved these changes

2023-11-08 09:30 UTC, merged